CREATE TABLE DRIVER_PERSONAL(DRIVER_ID NUMBER(5),DRIVER_NAME NUMBER(5), ADDRESS1 VARCHAR2(100),DISTRICT1 NUMBER(5),STATE1 NUMBER(5),ADDRESS2 VARCHAR2(100),DISTRICT2 NUMBER(5),STATE2 NUMBER(5),MOBILE_NO VARCHAR2(15),RESIDENTIAL_NO1 VARCHAR2(10),RESIDENTIAL_NO2 NUMBER(10),SALARY VARCHAR2(5),COMMUNITY NUMBER(5),CASTE VARCHAR2(30),RELIGION NUMBER(5),DOB DATE,DOJ DATE,DEL_IND VARCHAR2(1));

CREATE TABLE DRIVER_OFFICIAL( DRIVER_ID NUMBER(5),INSTITUTE_NAME NUMBER(5),DEPT NUMBER(5),EDUCATIONAL_QUALIFICATION VARCHAR2(10),MARKS NUMBER(5,2),TRANSPORT_EXP VARCHAR2 (15),NON_TRANSPORT_EXP VARCHAR2(15), DESC_NON_TRANSPORT_EXP VARCHAR2(30),BLOOD_GROUP NUMBER(5), LICENCE_NO VARCHAR2 (15),INSURANCE_NO VARCHAR2(10),DEL_IND VARCHAR2(1));

CREATE TABLE DRIVER_LICENCE(DRIVER_ID NUMBER(5),DRIVER_NAME NUMBER(5),LICENCE_NO VARCHAR2(15),BATCH_NO VARCHAR2(15),LICENCE_DATE DATE,VALID_TILL DATE,CATEGORY  VARCHAR2(20),PRE_LICENCE_EXPIRY DATE,ENDORSEMENT VARCHAR2(20),PUNISHMENTS VARCHAR2(100),DEL_IND VARCHAR2(1));

CREATE TABLE DRIVER_INSURANCE(DRIVER_ID NUMBER(5),DRIVER_NAME NUMBER(5),POLICY_NO VARCHAR2(15),POLICY_NAME VARCHAR2(20),COVERAGE VARCHAR2(100),PREMIUM_AMT NUMBER(5),INSUR_CMPY_ADDRESS VARCHAR2(100),VALID_FROM DATE,VALID_TO DATE,TIEUP_HOSPITALS VARCHAR2(100),COMPENSATION_AMT NUMBER(10),HOSPITAL_AMT NUMBER(10),BUFFER_AMT NUMBER(10),CONSTRAINTS VARCHAR2(300),DEL_IND VARCHAR2(1));

CREATE TABLE DRIVER_LEAVE(DRIVER_ID NUMBER(5),DRIVER_NAME NUMBER(5),DEPT NUMBER(5),NO_DAYS_LEAVE NUMBER(2),LEAVE_ALREADY_TAKEN NUMBER(2),CASUAL_LEAVE NUMBER(2),COMPENSATION_LEAVE NUMBER(2),MEDICAL_LEAVE NUMBER(2),VACATION_LEAVE NUMBER(2),DEL_IND VARCHAR2(1));

CREATE TABLE BUS_ALLOTMENT(INSTITUTE_NAME NUMBER(5),VEHICLE_ID NUMBER(5),DRIVER_ID NUMBER(5),DRIVER_NAME NUMBER(5),VEHICLE_ALLOTED_DATE DATE,ROUTE_NO VARCHAR2(3),KM_PERDAY NUMBER(5),STARTING_PLACE VARCHAR2(20),VIA VARCHAR2(20),LAST_STOP VARCHAR2(20),HALT_PLACE VARCHAR2(20),HALT_RES_PHONENO VARCHAR2(15),HALT_OFFICE_PHONENO VARCHAR2(15),PERMITTED_DISTRICT VARCHAR2(20),DEL_IND VARCHAR2(1));

CREATE TABLE VEHICLE_INSURANCE(INSTITUTE_NAME NUMBER(5),VEHICLE_ID NUMBER(5),VEHICLE_TYPE NUMBER(5),VEHICLE_MODEL NUMBER(10),MARKET_VALUE NUMBER(10),INSURANCE_FROM DATE,INSURANCE_TO DATE,EXISTING_COMPANY_NAME VARCHAR2(20),EXISTING_VALUE_INSURED NUMBER(10),EXISTING_PREMIUM_AMT NUMBER(10),PROPOSED_COMPANY_NAME VARCHAR2(20),PROPOSED_VALUE_INSURED NUMBER(10),PROPOSED_PREMIUM_AMT NUMBER(10));

CREATE TABLE ROAD_TAX (INSTITUTE_NAME NUMBER(5),VEHICLE_TYPE NUMBER(5),VEHICLE_ID NUMBER(5),SEAT_CAPACITY  NUMBER(4),RATE_PER_SEAT NUMBER(6,2),TAX_AMT NUMBER(8,2),TAX_PERIOD NUMBER(4),REDUCTION_ALLOWED NUMBER(5),REDUCTION_PERCENTAGE NUMBER(4,2),REDUCTION_AMOUNT NUMBER(8,2),GROSS_AMT NUMBER(10,2),SUBCHARGE_PERCENTAGE NUMBER(4,2),SUBCHARGE_AMT NUMBER(6,2),GRAND_TOTAL NUMBER(12,2));

CREATE TABLE BREAKDOWN_DETAILS(BREAKDOWN_DATE DATE,BREAKDOWN_TIME VARCHAR2(10),BREAKDOWN_PLACE VARCHAR2(20),DRIVER_ID NUMBER(5),DRIVER_NAME NUMBER(5),INSTITUTE_NAME NUMBER(5),VEHICLE_ID NUMBER(5),ROUTE_NO VARCHAR2(3),BREAKDOWN_NATURE VARCHAR2(100),ALTERNATE_VEHICLE_ID NUMBER(5),ALTERNATE_DRIVER_ID NUMBER(5),ALTERNATE_DRIVER_NAME NUMBER(5),REMARKS VARCHAR2(100));

CREATE TABLE EQUIPMENT_DETAILS(VEHICLE_ID NUMBER(5),EQUIPMENT_NAME NUMBER(5),QUANTITY NUMBER(5));

CREATE TABLE VEHICLE_PURCHASE(PURCHASE_DATE DATE,MANUFACTURING_DATE DATE,INSTITUTE_NAME NUMBER(5),VEHICLE_ID VARCHAR2(20),PRICE NUMBER(10,2),SUPPLIER_NAME VARCHAR2(20),VEHICLE_TYPE NUMBER(5),MAKE VARCHAR2(20),CHASSIS_NO VARCHAR2(20),ENGINE_NO VARCHAR2(20),BODY_TYPE VARCHAR2(20),TANK_CAPACITY NUMBER(10),SEAT_CAPACITY NUMBER(5),WHEEL_BASE VARCHAR2(20),VEHICLE_STATUS NUMBER(5),ROADTAX_PAID NUMBER(5),ROADTAX_FROM DATE,ROADTAX_TO DATE,INSURANCE_PAID NUMBER(5),INSURANCE_FROM DATE,INSURANCE_TO DATE,INSURANCE_CMPY_NAME VARCHAR(50),FC_EXPIRY_DATE DATE,VALID_PERMIT_DATE DATE,KM_TRAVELLED VARCHAR2(1),DEL_IND VARCHAR2(1));

CREATE TABLE ACCIDENT_DETAILS(ACCIDENT_DATE DATE,ACCIDENT_TIME VARCHAR2(15),ACCIDENT_PLACE VARCHAR2(20),NEAR_POLICE_STATION VARCHAR2(25),VEHICLE_ID NUMBER(5),VEHICLE_TYPE NUMBER)








