// LOOKUP FOR SPARE

create table SPARELOOKUP(ID NUMBER(5),CODE VARCHAR2(30),CODETYPE VARCHAR2(30));

// FOR INSERTING VALUES INTO SPARE LOOKUP

insert into SPARELOOKUP values(1,'Spare','Lever');

insert into SPARELOOKUP values(2,'Spare','Nut');

 insert into SPARELOOKUP values(3,'Spare','Bolt');


insert into SPARELOOKUP values(4,'Lever','Lever1');

insert into SPARELOOKUP values(5,'Lever','Lever2');

insert into SPARELOOKUP values(6,'Nut','Nut 12');

 insert into SPARELOOKUP values(7,'Bolt','Bolt 4x4');