CREATE TABLE OILGREASEREQUISITION(JOBID NUMBER ,REQDATE DATE,REQFROM VARCHAR2(20),REQITEM VARCHAR2(10),BRANDNAME VARCHAR2(20),BRANDTYPE VARCHAR2(20),AVAILABLEQTY NUMBER,NEEDEDQTY NUMBER);
CREATE SEQUENCE CODESEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE TABLE STORE_SUPPLIER(SID NUMBER ,JID NUMBER,BILL_DATE DATE,BILL_NO NUMBER,PURCHASE_DATE DATE
,COMPANY_NAME VARCHAR2(30),PLACE VARCHAR2(15),GOODS_TYPE VARCHAR2(15),BILL_PASSED NUMBER);
CREATE TABLE STORE_COMMON_TRANSACTION(JID NUMBER, SID NUMBER, BRAND_NAME VARCHAR2(30), BRAND_TYPE VARCHAR2(30), PARTNUMBER NUMBER,QTY_PURCHASED NUMBER, UNIT_PRICE NUMBER(10,2),  VAT_PERCENT NUMBER(10,2), VAT_AMOUNT NUMBER(10,2),  ADDTIONAL_AMT NUMBER(10,2), AMOUNT NUMBER(10,2));
CREATE TABLE STORE_PAINT_SPARE_GREASE_OIL(JID NUMBER, SID NUMBER, BRAND_NAME VARCHAR2(30), BRAND_TYPE VARCHAR(30), AVAILABILITY NUMBER);
CREATE TABLE OILGREASEREQUISITION(JID NUMBER,REQDATE DATE,REQFROM VARCHAR2(30),REQITEM NUMBER,BRANDNAME NUMBER,BRANDTYPE NUMBER,AVAILABLEQTY NUMBER,NEEDEDQTY NUMBER);
CREATE TABLE ADDRESS (COMPANY_NAME VARCHAR2(50), OWNER_NAME VARCHAR2(30), ADDRESS VARCHAR2(100), PLACE VARCHAR2(30), PHONE_NO VARCHAR2(30));
CREATE TABLE SUBPARTNO(PARTNO VARCHAR2(2),SPECIFIC VARCHAR2(2),ITEMNAME VARCHAR2(15));

SELECT CODESEQ.NEXTVAL FROM DUAL;
SELECT * FROM STORELOOKUP ORDER BY CODE;


insert into jobattribute1 values('&jobname',&taskcount,&attributeid);
INSERT INTO USERTAB1 VALUES(&USERID,'&USERNAME','&ROLE');
INSERT INTO STORELOOKUP VALUES(&CODE,'&CTYPE','&DESCRIPTION');
INSERT INTO SUBPARTNO VALUES('&PARTNO','&SPECIFIC','&ITEMNAME');

DELETE FROM TASKTAB1;
DELETE FROM OILGREASEREQUISITION;
DELETE FROM JOBTAB1;


UPDATE TASKTAB1 SET STATUS=0 WHERE TASKNAME='OilGreaseRequisitionForm_approve';
COMMIT;
UPDATE TASKTAB1 SET STATUS=0 WHERE TASKNAME='OilGreaseRequisitionForm_purchase';
COMMIT;


DROP TABLE STORE_COMMON_TRANSACTION;
DROP TABLE STORE_PAINT_SPARE_GREASE_OIL;
DROP TABLE ADDRESS;
DROP TABLE OILGREASEREQUISITION;



